### ISSUE TITLE
Unit not shown in Datapoint Graph

### ISSUE THREAD

**Issue by ButKor** [SoftwareAG/cumulocity-community-plugins#15]
**Describe the bug**
I have the Datapoint Graph plugin deployed to my Cockpit and configured data points. I have assigned the Datapoint Templates when setting up the widget. The measurements are having "ms" as unit and also the assigned Datapoint template has a Unit configured. However, I can't see unit displayed. 

Is this a bug or did I miss a configuration?

**To Reproduce**
1. Create Datapoint template including unit
2. Push Measurements including unit
3. Setup Datapoint Graph and assign datapoint template
4. Check if units are shown in Graph 

**Expected behavior**
Units are shown when hovering over graph

**Screenshots**
<img width="884" alt="widget_configuration" src="https://github.com/SoftwareAG/cumulocity-community-plugins/assets/20768097/b5edf389-c71e-4b16-8843-5ddbe76b988f">

<img width="772" alt="datapoint_graph" src="https://github.com/SoftwareAG/cumulocity-community-plugins/assets/20768097/6597a08a-c932-4484-ab9a-570f95e5c230">

**Desktop (please complete the following information):**
 - OS: ios
 - Browser Firefox

**Comment by janhommes** [comment]
Can confirm, the unit is missing on the tooltip and needs to be added.
